### ISSUE TITLE
Using without composer?

### ISSUE THREAD

**Issue by robynitp** [JustBlackBird/handlebars.php-helpers#1] opened 2015-06-08 01:10 UTC
What's the best way to use this if I'm not using composer? Is there an autoloader? Do I need to write my own?

Alternately, if I were to only need one subset, what are the minimum files I'd need to manually include? Would it be `Date/FormatDateHelper.php` and Date/Helpers.php` ?

Thanks for your help.

**Comment by JustBlackBird** [comment] 2015-06-08 08:59
There is no autoloader bundled with the library, but the library follows [PSR-4 standard](http://www.php-fig.org/psr/psr-4/) so you can use a third-party PSR-4 compatible autoloader. For example, there is `Psr4ClassLoader` in Symfony2 [ClassLoader package](https://github.com/symfony/ClassLoader).

Frankly, I don't recommend you to manually include files of the library. It's better to use an autoloader. Nevertheless, if you still want to go this way you should include the following files to make Date helpers work:
- `Date/FormatDateHelper.php`
- `Date/Helpers.php`
- Any required files from Handlebars.php

**Comment by robynitp** [comment] 2015-06-08 12:30
Thank you for the tips!

**Comment by JustBlackBird** [comment] 2015-06-08 12:33
You're welcome. It seems that the problem is solved, so I'm closing the issue.

**Closed as completed by JustBlackBird** 2015-06-08 12:33 UTC
Labels: question
